/**
 * Generated by Seraphim Compiler
 * SERAPH Operating System - MC26
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <setjmp.h>

/* SERAPH VOID value definitions */
#define SERAPH_VOID_U8   ((uint8_t)0xFF)
#define SERAPH_VOID_U16  ((uint16_t)0xFFFF)
#define SERAPH_VOID_U32  ((uint32_t)0xFFFFFFFF)
#define SERAPH_VOID_U64  ((uint64_t)0xFFFFFFFFFFFFFFFF)
#define SERAPH_VOID_I8   ((int8_t)-1)
#define SERAPH_VOID_I16  ((int16_t)-1)
#define SERAPH_VOID_I32  ((int32_t)-1)
#define SERAPH_VOID_I64  ((int64_t)-1)
#define SERAPH_VOID_PTR  ((void*)0)

/* VOID checking macros */
#define SERAPH_IS_VOID_U8(x)  ((x) == SERAPH_VOID_U8)
#define SERAPH_IS_VOID_U16(x) ((x) == SERAPH_VOID_U16)
#define SERAPH_IS_VOID_U32(x) ((x) == SERAPH_VOID_U32)
#define SERAPH_IS_VOID_U64(x) ((x) == SERAPH_VOID_U64)
#define SERAPH_IS_VOID_I8(x)  ((x) == SERAPH_VOID_I8)
#define SERAPH_IS_VOID_I16(x) ((x) == SERAPH_VOID_I16)
#define SERAPH_IS_VOID_I32(x) ((x) == SERAPH_VOID_I32)
#define SERAPH_IS_VOID_I64(x) ((x) == SERAPH_VOID_I64)
#define SERAPH_IS_VOID_PTR(x) ((x) == SERAPH_VOID_PTR)

/* Generic VOID check (uses _Generic in C11) */
#define SERAPH_IS_VOID(x) _Generic((x), \
    uint8_t:  SERAPH_IS_VOID_U8(x), \
    uint16_t: SERAPH_IS_VOID_U16(x), \
    uint32_t: SERAPH_IS_VOID_U32(x), \
    uint64_t: SERAPH_IS_VOID_U64(x), \
    int8_t:   SERAPH_IS_VOID_I8(x), \
    int16_t:  SERAPH_IS_VOID_I16(x), \
    int32_t:  SERAPH_IS_VOID_I32(x), \
    int64_t:  SERAPH_IS_VOID_I64(x), \
    default:  SERAPH_IS_VOID_PTR(x))

/* Panic function */
extern void seraph_panic(const char* msg) __attribute__((noreturn));

/* Atlas (persistent storage) types */
typedef struct Seraph_Atlas Seraph_Atlas;
typedef struct Seraph_Atlas_Transaction Seraph_Atlas_Transaction;
extern Seraph_Atlas __atlas;
extern Seraph_Atlas_Transaction* seraph_atlas_begin(Seraph_Atlas* atlas);
extern void seraph_atlas_commit(Seraph_Atlas* atlas, Seraph_Atlas_Transaction* tx);
extern void seraph_atlas_rollback(Seraph_Atlas* atlas, Seraph_Atlas_Transaction* tx);

/* Aether (network) types */
typedef struct Seraph_Aether Seraph_Aether;
typedef struct Seraph_Aether_Context Seraph_Aether_Context;
extern Seraph_Aether __aether;
extern Seraph_Aether_Context* seraph_aether_begin(Seraph_Aether* aether);
extern void seraph_aether_end(Seraph_Aether* aether, Seraph_Aether_Context* ctx);

/* Slice type */
typedef struct { void* data; size_t len; } Seraph_Slice;

/* Fixed-point types */
typedef int64_t Seraph_Scalar;  /* Q32.32 fixed-point */
typedef struct { int64_t real; int64_t dual; } Seraph_Dual;
typedef struct { int64_t w; int64_t x; int64_t y; int64_t z; } Seraph_Galactic;

/* Forward declarations */
typedef struct Point Point;
int32_t main(void);

struct Point {
    int32_t x;
    int32_t y;
};

int32_t main(void) {
    struct Point p = (struct Point){ .x = 10LL, .y = 20LL };
    int32_t a = p.x;
    int32_t b = p.y;
    return (a + b);
}
